// Pattern: Backtracking
// Author:  Ismael Sallami Moreno
// Source:  written for this repository. Not extracted from earlier work,
//          unlike everything under patterns/ - there is no prior commit
//          history to link to for this file.
// Verify:  g++ -std=c++20 -O1 -Wall -o /tmp/check backtracking.cpp && /tmp/check
//          The file asserts its own behaviour, so a silent run is a pass.

#include <algorithm>
#include <cassert>
#include <string>
#include <vector>

using namespace std;

// Backtracking is depth-first search over partial solutions: extend, recurse, undo. The
// undo is what makes one shared buffer enough instead of a copy per branch, and pruning
// early is what separates it from brute force.

// Every subset of a set. There are 2^n of them, so nothing can beat exponential here - the
// structure is just "include this element or do not".
void collect_subsets(const vector<int>& values, size_t index, vector<int>& current,
                     vector<vector<int>>& out) {
  if (index == values.size()) { out.push_back(current); return; }
  collect_subsets(values, index + 1, current, out);  // skip
  current.push_back(values[index]);
  collect_subsets(values, index + 1, current, out);  // take
  current.pop_back();                               // the undo
}

vector<vector<int>> subsets(const vector<int>& values) {
  vector<vector<int>> out;
  vector<int> current;
  collect_subsets(values, 0, current, out);
  return out;
}

// Every permutation, generated by swapping into place. Swapping rather than copying keeps
// the space at O(n) and makes the undo a second swap.
void collect_permutations(vector<int>& values, size_t index, vector<vector<int>>& out) {
  if (index == values.size()) { out.push_back(values); return; }
  for (size_t i = index; i < values.size(); ++i) {
    swap(values[index], values[i]);
    collect_permutations(values, index + 1, out);
    swap(values[index], values[i]);  // the undo
  }
}

vector<vector<int>> permutations(vector<int> values) {
  vector<vector<int>> out;
  collect_permutations(values, 0, out);
  return out;
}

// Combinations summing to a target, with unlimited reuse of each candidate. Passing the
// same index down allows reuse; starting the loop at `from` stops the same multiset being
// produced in several orders, which is the pruning that matters here.
void collect_sums(const vector<int>& candidates, int remaining, size_t from,
                  vector<int>& current, vector<vector<int>>& out) {
  if (remaining == 0) { out.push_back(current); return; }
  for (size_t i = from; i < candidates.size(); ++i) {
    if (candidates[i] > remaining) continue;  // prune: cannot reach zero from here
    current.push_back(candidates[i]);
    collect_sums(candidates, remaining - candidates[i], i, current, out);
    current.pop_back();
  }
}

vector<vector<int>> combination_sum(vector<int> candidates, int target) {
  sort(candidates.begin(), candidates.end());
  vector<vector<int>> out;
  vector<int> current;
  collect_sums(candidates, target, 0, current, out);
  return out;
}

// N-queens. One queen per row by construction, so only columns and the two diagonal
// directions need tracking. Constant-time conflict checks are what make the pruning cheap
// enough to matter: the search visits a tiny fraction of the n^n placements.
class NQueens {
  int n;
  vector<bool> column, rising, falling;
  int solutions = 0;

  void place(int row) {
    if (row == n) { ++solutions; return; }
    for (int col = 0; col < n; ++col) {
      const int up = row + col;          // one diagonal direction
      const int down = row - col + n;    // the other, shifted to stay non-negative
      if (column[col] || rising[up] || falling[down]) continue;
      column[col] = rising[up] = falling[down] = true;
      place(row + 1);
      column[col] = rising[up] = falling[down] = false;  // the undo
    }
  }

 public:
  explicit NQueens(int n)
      : n(n), column(n, false), rising(2 * n, false), falling(2 * n, false) {}

  int count() {
    solutions = 0;
    place(0);
    return solutions;
  }
};

int main() {
  assert(subsets({1, 2, 3}).size() == 8);   // 2^3
  assert(subsets({}).size() == 1);          // the empty set has one subset
  assert(permutations({1, 2, 3}).size() == 6);   // 3!
  assert(permutations({1}).size() == 1);

  vector<vector<int>> sums = combination_sum({2, 3, 6, 7}, 7);
  assert(sums.size() == 2);  // {2,2,3} and {7}
  assert(combination_sum({2}, 1).empty());
  // Unlimited reuse: 1 four times.
  assert(combination_sum({1}, 4).size() == 1);

  // The known solution counts for n-queens, which is the standard check.
  assert(NQueens(1).count() == 1);
  assert(NQueens(2).count() == 0);  // no solution
  assert(NQueens(3).count() == 0);
  assert(NQueens(4).count() == 2);
  assert(NQueens(5).count() == 10);
  assert(NQueens(6).count() == 4);
  assert(NQueens(7).count() == 40);
  assert(NQueens(8).count() == 92);
  return 0;
}
